query-types = ["multi-cols-point-query", "single-col-point-query"]
report-dir = "/Users/zhangyuanjia/Workspace/go/src/github.com/qw4990/OptimizerTester/cetest/test"
n = 1000

[[datasets]]
name = "zipfx"
db = "zipfx"
label = "zipf1.5-1000000rows"

[[instances]]
addr = "127.0.0.1"
port = 4000
user = "root"
password = ""
label = "master"

