query-types = ["multi-cols-point-query", "single-col-point-query"]
report-dir = "/tmp/xxx"
n = 1000

[[datasets]]
name = "imdb"
db = "imdb"
label = "imdb"

[[datasets]]
name = "tpcc"
db = "tpcc10G"
label = "tpcc10G"

[[datasets]]
name = "tpcc"
db = "tpcc50G"
label = "tpcc50G"

[[instances]]
addr = "127.0.0.1"
port = 4000
user = "root"
password = "123456"
label = "v4.0"

[[instances]]
addr = "127.0.0.1"
port = 4001
user = "root"
password = "123456"
label = "master"