query-types = ["multi-cols-point-query", "single-col-point-query"]
report-dir = "/Users/zhangyuanjia/Workspace/go/src/github.com/qw4990/OptimizerTester/cetest/test"
n = 1000

[[datasets]]
name = "mock"
db = "mock"
label = "mock1G"

[[datasets]]
name = "mock"
db = "mock"
label = "mock10G"

[[instances]]
addr = "127.0.0.1"
port = 4000
user = "root"
password = ""
label = "master"

[[instances]]
addr = "127.0.0.1"
port = 4000
user = "root"
password = ""
label = "v4.0.12"
